# Generated by Django 6.0 on 2026-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recognition/images/', verbose_name='Зображення')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='Результат аналізу')),
            ],
            options={
                'verbose_name': 'Аналіз зображення',
                'verbose_name_plural': 'Аналізи зображень',
            },
        ),
    ]
