# Generated by Django 6.0 on 2026-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_vision', '0002_videoanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/', verbose_name='Аудіофайл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат аналізу')),
            ],
            options={
                'verbose_name': 'Аудіозапис',
                'verbose_name_plural': 'Аудіозаписи',
            },
        ),
    ]
